// <auto-generated />
using System;
using DevIO.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevIO.Data.Migrations;

[DbContext(typeof(CustomDbContext))]
partial class CustomDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.8")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("DevIO.Business.Models.Address", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("AdditionalInfo")
                    .IsRequired()
                    .HasColumnType("nvarchar(250)");

                b.Property<string>("City")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("District")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Number")
                    .IsRequired()
                    .HasColumnType("varchar(50)");

                b.Property<string>("PostalCode")
                    .IsRequired()
                    .HasColumnType("varchar(8)");

                b.Property<string>("State")
                    .IsRequired()
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Street")
                    .IsRequired()
                    .HasColumnType("nvarchar(200)");

                b.Property<Guid>("SupplierId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("SupplierId")
                    .IsUnique();

                b.ToTable("Addresses", (string)null);
            });

        modelBuilder.Entity("DevIO.Business.Models.Product", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(1000)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(200)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");

                b.Property<Guid>("SupplierId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("SupplierId");

                b.ToTable("Products", (string)null);
            });

        modelBuilder.Entity("DevIO.Business.Models.Supplier", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Document")
                    .IsRequired()
                    .HasColumnType("varchar(14)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(100)");

                b.Property<int>("SupplierType")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("Suppliers", (string)null);
            });

        modelBuilder.Entity("DevIO.Business.Models.Address", b =>
            {
                b.HasOne("DevIO.Business.Models.Supplier", "Supplier")
                    .WithOne("Address")
                    .HasForeignKey("DevIO.Business.Models.Address", "SupplierId")
                    .IsRequired();

                b.Navigation("Supplier");
            });

        modelBuilder.Entity("DevIO.Business.Models.Product", b =>
            {
                b.HasOne("DevIO.Business.Models.Supplier", "Supplier")
                    .WithMany("Products")
                    .HasForeignKey("SupplierId")
                    .IsRequired();

                b.Navigation("Supplier");
            });

        modelBuilder.Entity("DevIO.Business.Models.Supplier", b =>
            {
                b.Navigation("Address")
                    .IsRequired();

                b.Navigation("Products");
            });
#pragma warning restore 612, 618
    }
}

